import "./globals.css";
import { Manrope } from "next/font/google";
import Navbar from "@/components/Navbar";
import ProviderTheme from "@/components/HOC/ProviderTheme";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";

const font = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Food Landing Page",
  description: "Generated by Next.js, TypeScript && TailwindCSS",
  icons: {
    icon: "/images/a.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${font.className} antialiased transition-all duration-300 transform`}
      >
        <ReduxProvider>
          <ProviderTheme>
            <Navbar />
            <main className="pt-24 container mx-auto px-2 sm:px-3 md:px-6 lg:px-12">
              {children}
            </main>
            <Footer />
            <Toaster
              position="bottom-center"
              toastOptions={{
                duration: 2000,
                style: {
                  background: "#363636",
                  color: "#fff",
                },
              }}
            />
          </ProviderTheme>
        </ReduxProvider>
      </body>
    </html>
  );
}
