import { RestaurantProps } from "@/types/types";

export const restaurants: RestaurantProps[] = [
  {
    id: "1",
    name: "Pizza Hut",
    image: "/images/r1.jpg",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: 25,
    deliveryFee: 2.99,
    minOrder: 10,
    description: "Famous for its wide variety of cheesy Italian-style pizzas.",
    isOpen: true,
    price: 12.99,
  },
  {
    id: "2",
    name: "Chipotle Mexican Grill",
    image: "/images/r2.jpg",
    rating: 4.7,
    cuisine: "Mexican",
    deliveryTime: 35,
    deliveryFee: 3.99,
    minOrder: 15,
    description:
      "Fresh burritos, tacos, and bowls made with bold Mexican flavors.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "3",
    name: "McDonald's Burgers",
    image: "/images/r3.jpg",
    rating: 4.3,
    cuisine: "American",
    deliveryTime: 30,
    deliveryFee: 2.49,
    minOrder: 12,
    description: "World-famous fast food burgers, fries, and soft drinks.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "4",
    name: "The Baked Bear San Francisco",
    image: "/images/r4.jpg",
    rating: 4.2,
    cuisine: "Desserts",
    deliveryTime: 20,
    deliveryFee: 1.99,
    minOrder: 8,
    description: "Custom ice cream sandwiches and baked dessert creations.",
    isOpen: true,
    price: 5.99,
  },
  {
    id: "5",
    name: "Shake Shack",
    image: "/images/r5.jpg",
    rating: 4.6,
    cuisine: "American",
    deliveryTime: 28,
    deliveryFee: 2.75,
    minOrder: 9,
    description:
      "Modern American-style burgers, crinkle-cut fries, and shakes.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "6",
    name: "Chubby Noodle Chinese",
    image: "/images/r6.jpg",
    rating: 4.4,
    cuisine: "Chinese",
    deliveryTime: 32,
    deliveryFee: 3.25,
    minOrder: 13,
    description: "Classic Chinese noodles, dumplings, and stir-fry dishes.",
    isOpen: true,
    price: 11.99,
  },
  {
    id: "7",
    name: "Onion Pizza",
    image:
      "https://img.freepik.com/free-photo/seafood-pizza_74190-5944.jpg?w=996&t=st=1693062328~exp=1693062928~hmac=53fd9ad496580db41c6ca8066510cd89c6b0a0389de8bb6b875a78a1eda09cb5",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: 30,
    deliveryFee: 2.5,
    minOrder: 10,
    description: "A delicious pizza topped with fresh onions and rich flavors.",
    isOpen: true,
    price: 8.5,
  },
  {
    id: "8",
    name: "Margherita Pizza",
    image:
      "https://w7.pngwing.com/pngs/339/55/png-transparent-pizza-margherita-italian-cuisine-hot-dog-pizza-cheese-pizza-thumbnail.png",
    rating: 4.2,
    cuisine: "Italian",
    deliveryTime: 28,
    deliveryFee: 2.0,
    minOrder: 9,
    description: "Classic Italian pizza with fresh tomatoes and mozzarella.",
    isOpen: true,
    price: 7.99,
  },
  {
    id: "9",
    name: "Pepperoni Pizza",
    image:
      "https://w7.pngwing.com/pngs/21/55/png-transparent-pepperoni-pizza-margarita-pizza-margherita-italian-cuisine-tomato-pizza-food-cheese-recipe-thumbnail.png",
    rating: 4.6,
    cuisine: "Italian",
    deliveryTime: 32,
    deliveryFee: 2.5,
    minOrder: 11,
    description: "Spicy pepperoni, melted cheese, and tangy tomato sauce.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "10",
    name: "Mushroom and Spinach Pizza",
    image:
      "https://w7.pngwing.com/pngs/569/109/png-transparent-pizza-with-vegetables-and-mushroom-toppings-sicilian-pizza-california-style-pizza-pizza-margherita-vegetarian-cuisine-pizza-food-recipe-gourmet-thumbnail.png",
    rating: 4.2,
    cuisine: "Mexican",
    deliveryTime: 30,
    deliveryFee: 2.2,
    minOrder: 10,
    description: "Earthy mushrooms and spinach topped with cheese blend.",
    isOpen: true,
    price: 7.68,
  },
  {
    id: "11",
    name: "BBQ Chicken Pizza",
    image:
      "https://w7.pngwing.com/pngs/843/171/png-transparent-pizza-73-restaurant-catupiry-chicken-as-food-pizza-baked-goods-food-recipe-thumbnail.png",
    rating: 4.8,
    cuisine: "Mexican",
    deliveryTime: 34,
    deliveryFee: 2.7,
    minOrder: 12,
    description: "Tender chicken, BBQ sauce, red onions, and cheese blend.",
    isOpen: true,
    price: 10.99,
  },
  {
    id: "12",
    name: "Classic Pancakes",
    image:
      "https://w7.pngwing.com/pngs/133/54/png-transparent-pancakes-served-on-plate-banana-pancakes-scrambled-eggs-breakfast-ihop-pancake-food-recipe-eating-thumbnail.png",
    rating: 4.5,
    cuisine: "American",
    deliveryTime: 20,
    deliveryFee: 1.5,
    minOrder: 6,
    description: "Fluffy pancakes with syrup and butter, a morning delight.",
    isOpen: true,
    price: 6.99,
  },
  {
    id: "13",
    name: "Egg and Bacon Croissant",
    image:
      "https://w7.pngwing.com/pngs/645/475/png-transparent-croissant-bread-croissant-muffin-brunch-bacon-egg-and-cheese-sandwich-bread-croissants-baked-goods-food-baking-thumbnail.png",
    rating: 4.2,
    cuisine: "Desserts",
    deliveryTime: 22,
    deliveryFee: 1.8,
    minOrder: 7,
    description: "Buttery croissant filled with eggs, bacon, and cheese.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "14",
    name: "Greek Yogurt Parfait",
    image:
      "https://w7.pngwing.com/pngs/683/103/png-transparent-frozen-yogurt-parfait-breakfast-yoghurt-fruit-salad-yogurt-frutti-di-bosco-food-breakfast-thumbnail.png",
    rating: 4.1,
    cuisine: "Desserts",
    deliveryTime: 18,
    deliveryFee: 1.2,
    minOrder: 5,
    description: "Layers of yogurt, berries, granola, and a drizzle of honey.",
    isOpen: true,
    price: 9.5,
  },
  {
    id: "15",
    name: "Avocado Toast",
    image:
      "https://w7.pngwing.com/pngs/400/603/png-transparent-toast-tostytosty-la-tosteria-menu-food-dish-avocado-toast-food-toast-avocado-toast-thumbnail.png",
    rating: 4.6,
    cuisine: "Chinese",
    deliveryTime: 24,
    deliveryFee: 1.9,
    minOrder: 8,
    description: "Creamy avocado on toast with sea salt and chili flakes.",
    isOpen: true,
    price: 11.99,
  },
  {
    id: "16",
    name: "Fruit and Nut Oatmeal",
    image:
      "https://w7.pngwing.com/pngs/20/725/png-transparent-grain-bowl-breakfast-cereal-muesli-corn-flakes-bowl-granola-food-breakfast-recipe-thumbnail.png",
    rating: 4.5,
    cuisine: "Chinese",
    deliveryTime: 20,
    deliveryFee: 1.5,
    minOrder: 7,
    description: "Hearty oatmeal with fruits, nuts, and a drizzle of honey.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "17",
    name: "Grilled Salmon",
    image:
      "https://w7.pngwing.com/pngs/875/111/png-transparent-north-fish-seafood-dish-smoked-salmon-restaurant-grilled-fish-hd-soup-food-seafood-thumbnail.png",
    rating: 4.5,
    cuisine: "American",
    deliveryTime: 30,
    deliveryFee: 2.8,
    minOrder: 12,
    description: "Grilled salmon served with herbs and roasted vegetables.",
    isOpen: true,
    price: 7.99,
  },
  {
    id: "18",
    name: "Chicken Alfredo Pasta",
    image:
      "https://w7.pngwing.com/pngs/756/828/png-transparent-taglierini-carbonara-fettuccine-alfredo-chicken-pasta-chicken-fillet-thumbnail.png",
    rating: 4.8,
    cuisine: "American",
    deliveryTime: 32,
    deliveryFee: 3.0,
    minOrder: 14,
    description: "Creamy Alfredo pasta with grilled chicken and Parmesan.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "19",
    name: "Vegetable Stir-Fry",
    image:
      "https://w7.pngwing.com/pngs/651/721/png-transparent-veggie-burger-vegetable-food-recipe-stir-frying-vegetables-frying-pan-frozen-vegetables-fruit-thumbnail.png",
    rating: 4.2,
    cuisine: "Chinese",
    deliveryTime: 26,
    deliveryFee: 2.5,
    minOrder: 10,
    description: "Colorful stir-fried veggies served over steamed rice.",
    isOpen: true,
    price: 6.5,
  },
  {
    id: "20",
    name: "Grilled Chicken Burrito Bowl",
    image:
      "https://w7.pngwing.com/pngs/575/331/png-transparent-burrito-taco-bell-mexican-cuisine-chipotle-mexican-grill-menu-thumbnail.png",
    rating: 4.6,
    cuisine: "Mexican",
    deliveryTime: 28,
    deliveryFee: 2.7,
    minOrder: 11,
    description: "Burrito bowl with chicken, beans, rice, and fresh toppings.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "21",
    name: "Mushroom Risotto",
    image:
      "https://w7.pngwing.com/pngs/47/171/png-transparent-chinese-noodles-hot-and-sour-soup-risotto-lomi-lamian-slippery-mushrooms-risotto-dusi-soup-food-recipe-thumbnail.png",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: 33,
    deliveryFee: 2.9,
    minOrder: 13,
    description: "Creamy risotto with sautéed mushrooms and cheese.",
    isOpen: true,
    price: 10.99,
  },
  {
    id: "22",
    name: "Cheese and Crackers Platter",
    image:
      "https://w7.pngwing.com/pngs/47/171/png-transparent-chinese-noodles-hot-and-sour-soup-risotto-lomi-lamian-slippery-mushrooms-risotto-dusi-soup-food-recipe-thumbnail.png",
    rating: 4.3,
    cuisine: "American",
    deliveryTime: 18,
    deliveryFee: 1.6,
    minOrder: 6,
    description:
      "Selection of artisan cheeses with crispy crackers and fruits.",
    isOpen: true,
    price: 7.0,
  },
  {
    id: "23",
    name: "Crispy Chicken Wings",
    image:
      "https://w7.pngwing.com/pngs/204/32/png-transparent-crispy-fried-chicken-karaage-chicken-nugget-chicken-fingers-buffalo-wing-carrot-chilli-thumbnail.png",
    rating: 4.4,
    cuisine: "Italian",
    deliveryTime: 22,
    deliveryFee: 1.9,
    minOrder: 8,
    description: "Crispy seasoned wings with your choice of sauce.",
    isOpen: true,
    price: 8.0,
  },
  {
    id: "24",
    name: "Paneer Tikka Skewers",
    image:
      "https://w7.pngwing.com/pngs/816/163/png-transparent-grilled-skewered-meat-bakery-paneer-tikka-indian-cuisine-vegetarian-cuisine-cake-food-baking-cake-decorating-thumbnail.png",
    rating: 4.9,
    cuisine: "Italian",
    deliveryTime: 26,
    deliveryFee: 2.1,
    minOrder: 9,
    description: "Marinated paneer grilled and served with mint chutney.",
    isOpen: true,
    price: 9.0,
  },
  {
    id: "25",
    name: "Hummus and Veggie Platter",
    image:
      "https://w7.pngwing.com/pngs/356/675/png-transparent-falafel-lebanese-cuisine-take-out-mediterranean-cuisine-hummus-bed-miscellaneous-furniture-food-thumbnail.png",
    rating: 4.4,
    cuisine: "Mexican",
    deliveryTime: 20,
    deliveryFee: 1.7,
    minOrder: 7,
    description: "Smooth hummus with vegetable sticks and pita bread.",
    isOpen: true,
    price: 8.5,
  },
  {
    id: "26",
    name: "Fruit Skewers",
    image:
      "https://w7.pngwing.com/pngs/435/847/png-transparent-pincho-canape-skewer-fruit-others-thumbnail.png",
    rating: 4.8,
    cuisine: "Desserts",
    deliveryTime: 18,
    deliveryFee: 1.3,
    minOrder: 5,
    description: "Juicy skewers with a colorful mix of fresh fruits.",
    isOpen: true,
    price: 7.5,
  },
];

export const restaurantData: RestaurantProps = {
  id: "1",
  name: "Pizza Hut",
  image: "/images/r1.jpg",
  rating: 4.5,
  cuisine: "Italian",
  deliveryTime: 25,
  deliveryFee: 2.99,
  minOrder: 10,
  description: "Famous for its wide variety of cheesy Italian-style pizzas.",
  isOpen: true,
};
