import { RestaurantProps } from "@/types/types";

export const restaurants: RestaurantProps[] = [
  {
    id: "1",
    name: "Pizza Hut",
    image: "/images/r1.jpg",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: 25,
    deliveryFee: 2.99,
    minOrder: 10,
    description: "Famous for its wide variety of cheesy Italian-style pizzas.",
    isOpen: true,
    price: 12.99,
  },
  {
    id: "2",
    name: "Chipotle Mexican Grill",
    image: "/images/r2.jpg",
    rating: 4.7,
    cuisine: "Mexican",
    deliveryTime: 35,
    deliveryFee: 3.99,
    minOrder: 15,
    description:
      "Fresh burritos, tacos, and bowls made with bold Mexican flavors.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "3",
    name: "McDonald's Burgers",
    image: "/images/r3.jpg",
    rating: 4.3,
    cuisine: "American",
    deliveryTime: 30,
    deliveryFee: 2.49,
    minOrder: 12,
    description: "World-famous fast food burgers, fries, and soft drinks.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "4",
    name: "The Baked Bear San Francisco",
    image: "/images/r4.jpg",
    rating: 4.2,
    cuisine: "Desserts",
    deliveryTime: 20,
    deliveryFee: 1.99,
    minOrder: 8,
    description: "Custom ice cream sandwiches and baked dessert creations.",
    isOpen: true,
    price: 5.99,
  },
  {
    id: "5",
    name: "Shake Shack",
    image: "/images/r5.jpg",
    rating: 4.6,
    cuisine: "American",
    deliveryTime: 28,
    deliveryFee: 2.75,
    minOrder: 9,
    description:
      "Modern American-style burgers, crinkle-cut fries, and shakes.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "6",
    name: "Chubby Noodle Chinese",
    image: "/images/r6.jpg",
    rating: 4.4,
    cuisine: "Chinese",
    deliveryTime: 32,
    deliveryFee: 3.25,
    minOrder: 13,
    description: "Classic Chinese noodles, dumplings, and stir-fry dishes.",
    isOpen: true,
    price: 11.99,
  },
  {
    id: "7",
    name: "Onion Pizza",
    // روابط Freepik بتنتهي صلاحيتها - استخدم رابط ثابت
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: 30,
    deliveryFee: 2.5,
    minOrder: 10,
    description: "A delicious pizza topped with fresh onions and rich flavors.",
    isOpen: true,
    price: 8.5,
  },
  {
    id: "8",
    name: "Margherita Pizza",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    rating: 4.2,
    cuisine: "Italian",
    deliveryTime: 28,
    deliveryFee: 2.0,
    minOrder: 9,
    description: "Classic Italian pizza with fresh tomatoes and mozzarella.",
    isOpen: true,
    price: 7.99,
  },
  {
    id: "9",
    name: "Pepperoni Pizza",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800",
    rating: 4.6,
    cuisine: "Italian",
    deliveryTime: 32,
    deliveryFee: 2.5,
    minOrder: 11,
    description: "Spicy pepperoni, melted cheese, and tangy tomato sauce.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "10",
    name: "Mushroom and Spinach Pizza",
    image: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800",
    rating: 4.2,
    cuisine: "Mexican",
    deliveryTime: 30,
    deliveryFee: 2.2,
    minOrder: 10,
    description: "Earthy mushrooms and spinach topped with cheese blend.",
    isOpen: true,
    price: 7.68,
  },
  {
    id: "11",
    name: "BBQ Chicken Pizza",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
    rating: 4.8,
    cuisine: "Mexican",
    deliveryTime: 34,
    deliveryFee: 2.7,
    minOrder: 12,
    description: "Tender chicken, BBQ sauce, red onions, and cheese blend.",
    isOpen: true,
    price: 10.99,
  },
  {
    id: "12",
    name: "Classic Pancakes",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800",
    rating: 4.5,
    cuisine: "American",
    deliveryTime: 20,
    deliveryFee: 1.5,
    minOrder: 6,
    description: "Fluffy pancakes with syrup and butter, a morning delight.",
    isOpen: true,
    price: 6.99,
  },
  {
    id: "13",
    name: "Egg and Bacon Croissant",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800",
    rating: 4.2,
    cuisine: "Desserts",
    deliveryTime: 22,
    deliveryFee: 1.8,
    minOrder: 7,
    description: "Buttery croissant filled with eggs, bacon, and cheese.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "14",
    name: "Greek Yogurt Parfait",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
    rating: 4.1,
    cuisine: "Desserts",
    deliveryTime: 18,
    deliveryFee: 1.2,
    minOrder: 5,
    description: "Layers of yogurt, berries, granola, and a drizzle of honey.",
    isOpen: true,
    price: 9.5,
  },
  {
    id: "15",
    name: "Avocado Toast",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800",
    rating: 4.6,
    cuisine: "Chinese",
    deliveryTime: 24,
    deliveryFee: 1.9,
    minOrder: 8,
    description: "Creamy avocado on toast with sea salt and chili flakes.",
    isOpen: true,
    price: 11.99,
  },
  {
    id: "16",
    name: "Fruit and Nut Oatmeal",
    image: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=800",
    rating: 4.5,
    cuisine: "Chinese",
    deliveryTime: 20,
    deliveryFee: 1.5,
    minOrder: 7,
    description: "Hearty oatmeal with fruits, nuts, and a drizzle of honey.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "17",
    name: "Grilled Salmon",
    image: "https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=800",
    rating: 4.5,
    cuisine: "American",
    deliveryTime: 30,
    deliveryFee: 2.8,
    minOrder: 12,
    description: "Grilled salmon served with herbs and roasted vegetables.",
    isOpen: true,
    price: 7.99,
  },
  {
    id: "18",
    name: "Chicken Alfredo Pasta",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
    rating: 4.8,
    cuisine: "American",
    deliveryTime: 32,
    deliveryFee: 3.0,
    minOrder: 14,
    description: "Creamy Alfredo pasta with grilled chicken and Parmesan.",
    isOpen: true,
    price: 9.99,
  },
  {
    id: "19",
    name: "Vegetable Stir-Fry",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800",
    rating: 4.2,
    cuisine: "Chinese",
    deliveryTime: 26,
    deliveryFee: 2.5,
    minOrder: 10,
    description: "Colorful stir-fried veggies served over steamed rice.",
    isOpen: true,
    price: 6.5,
  },
  {
    id: "20",
    name: "Grilled Chicken Burrito Bowl",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    rating: 4.6,
    cuisine: "Mexican",
    deliveryTime: 28,
    deliveryFee: 2.7,
    minOrder: 11,
    description: "Burrito bowl with chicken, beans, rice, and fresh toppings.",
    isOpen: true,
    price: 8.99,
  },
  {
    id: "21",
    name: "Mushroom Risotto",
    image: "https://images.unsplash.com/photo-1476124369491-c404f755c60b?w=800",
    rating: 4.5,
    cuisine: "Italian",
    deliveryTime: 33,
    deliveryFee: 2.9,
    minOrder: 13,
    description: "Creamy risotto with sautéed mushrooms and cheese.",
    isOpen: true,
    price: 10.99,
  },
  {
    id: "22",
    name: "Cheese and Crackers Platter",
    image: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800",
    rating: 4.3,
    cuisine: "American",
    deliveryTime: 18,
    deliveryFee: 1.6,
    minOrder: 6,
    description:
      "Selection of artisan cheeses with crispy crackers and fruits.",
    isOpen: true,
    price: 7.0,
  },
  {
    id: "23",
    name: "Crispy Chicken Wings",
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=800",
    rating: 4.4,
    cuisine: "Italian",
    deliveryTime: 22,
    deliveryFee: 1.9,
    minOrder: 8,
    description: "Crispy seasoned wings with your choice of sauce.",
    isOpen: true,
    price: 8.0,
  },
  {
    id: "24",
    name: "Paneer Tikka Skewers",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800",
    rating: 4.9,
    cuisine: "Italian",
    deliveryTime: 26,
    deliveryFee: 2.1,
    minOrder: 9,
    description: "Marinated paneer grilled and served with mint chutney.",
    isOpen: true,
    price: 9.0,
  },
  {
    id: "25",
    name: "Hummus and Veggie Platter",
    image: "https://images.unsplash.com/photo-1621503837513-a3a5763cd691?w=800",
    rating: 4.4,
    cuisine: "Mexican",
    deliveryTime: 20,
    deliveryFee: 1.7,
    minOrder: 7,
    description: "Smooth hummus with vegetable sticks and pita bread.",
    isOpen: true,
    price: 8.5,
  },
  {
    id: "26",
    name: "Fruit Skewers",
    image: "https://images.unsplash.com/photo-1564093497595-593b96d80180?w=800",
    rating: 4.8,
    cuisine: "Desserts",
    deliveryTime: 18,
    deliveryFee: 1.3,
    minOrder: 5,
    description: "Juicy skewers with a colorful mix of fresh fruits.",
    isOpen: true,
    price: 7.5,
  },
];

export const restaurantData: RestaurantProps = {
  id: "1",
  name: "Pizza Hut",
  image: "/images/r1.jpg",
  rating: 4.5,
  cuisine: "Italian",
  deliveryTime: 25,
  deliveryFee: 2.99,
  minOrder: 10,
  description: "Famous for its wide variety of cheesy Italian-style pizzas.",
  isOpen: true,
};
